# This is a basic workflow to help you get started with Actions

name: Flutter Build APK

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: build-app

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu:18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Setup Java Environment
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Install Flutter SDK
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.5'
      
    - name: Install dependencies
      run: flutter pub get

    - name: Check Payload
      run: echo ${{ github.event.client_payload.flavor }}

    - name: Run Analyzer
      run: flutter analyze
